### ISSUE TITLE
asyncio.rtfd.io isn't updating

### ISSUE THREAD

**Issue by brettcannon** [asyncio-docs/asyncio-doc#14]
The last build was a month ago but there have been changes made to this repository since then. Perhaps something went wrong with the webhook to trigger new builds?

**Comment by vstinner** [comment]
The ReadTheDocs webhook is still active and sending a test payload says "Okay, the test payload is on its way". (no obvious error)

I confirm that https://readthedocs.org/projects/asyncio/builds/ says that the latest build was 1 month ago.

At readthedocs.org, the asyncio project uses the repository https://github.com/asyncio-doc/asyncio-doc/ (Git).

Please give me your (Brett or anyone else) readthedocs.org identifier, so I can add you as other maintainers of the project.

I just forced a build as a temporary workaround...

**Comment by brettcannon** [comment]
My RTFD username is `brettcannon`.

**Comment by vstinner** [comment]
> My RTFD username is brettcannon.

Ok, I added you as the second maintainer.
