### ISSUE TITLE
No license for example code

### ISSUE THREAD

**Issue by stxlvt** [asyncio-docs/asyncio-doc#22]
I could not find any statement about what license the code examples have. Searching this github repo for the word "license" gave 0 results.

The lack of a license means that the authors reserve all rights by default, and it's illegal to copy or use the code in any way, except as allowed by the law, such as for fair use purposes, parody, etc.

This makes it much harder to use the example code as a starting point for a program, which seems to be the intended use. Since I can't legally copy-paste and modify, I'll instead have to learn from the code and then apply what I've learned in my own code. This might be a good thing for me in the end, because I will learn more and better that way, but it is probably asking too much from the intended users of these docs, and also invites unwitting copyright violations.

So, please include a visible statement about which license the examples are released under, or at least add a file called LICENSE, COPYING or similar to the repo with the license text.

**Comment by Mariatta** [comment]
Thanks @stxlvt. Yes I agree, there should be a license here.
@haypo, you created this repo initially. What's the license?

**Comment by vstinner** [comment]
I like Creative Commons license. I propose to use:
* CC BY-SA for the documentation: https://creativecommons.org/licenses/by-sa/4.0/
* CC0 for all code snippets (examples): https://creativecommons.org/publicdomain/zero/1.0/

**Comment by Mariatta** [comment]
Thanks @haypo. Hmm in GitHub we can only have one LICENSE file. 

Maybe the place to mention the above licenses is in README.rst.

**Comment by vstinner** [comment]
> Maybe the place to mention the above licenses is in README.rst.

If we choose a license, it should be written directly in the documentation.

For GitHub, if you can only choose one license, use the most restrictive by default, so CC BY-SA.
