### ISSUE TITLE
hello clock example

### ISSUE THREAD

**Issue by vahtras** [asyncio-docs/asyncio-doc#28]
The text describes two coroutines that run concurrently

*They run for ten minutes, during which the first coroutine is scheduled to run every second, while the second is scheduled to run every minute.*

I interpret this text as if both will run during ten minutes and then stop. What appears to happen though is that the second function,  `print_every_minute`,  runs for ten minutes while the first function `print_every_second` goes on for ever.  If this is the expected behavior for this piece of code, I find the text a bit misleading to an async novice like me and it could be clarified.

Best regards,
Olav

**Comment by hoh** [comment]
Thanks for your feedback. Do you find the fixes in PR #29 adequate ?

**Comment by manesioz** [comment]
Yes, I was just about to leave an issue about this exact same thing. #29 seems to fix it, unless the second count should be reset for each new minute in which case nested loops should do the trick. Either way its better than an infinite loop. Cheers, great docs otherwise

**Comment by vahtras** [comment]
Yes that'll be fine
