### ISSUE TITLE
Update to the Read the Docs webhook

### ISSUE THREAD

**Issue by brettcannon** [asyncio-docs/asyncio-doc#30]
If you have permissions and go to https://readthedocs.org/dashboard/asyncio/integrations/ you will notice there is no GitHub integration. Since [Read the Docs killed off their old integration](https://blog.readthedocs.com/webhook-deprecations/), a new webhook is necessary to be set by someone with admin privileges on this project.

**Comment by Mariatta** [comment]
Thanks. I've added the integration in RTD and configured the GitHub webhook.
