### ISSUE TITLE
Shut down asyncio.readthedocs

### ISSUE THREAD

**Issue by 1st1** [asyncio-docs/asyncio-doc#33]
asyncio has now an updated and easy to read documentation.  There's no need in another semi-official source -- https://asyncio.readthedocs.io/en/latest/; it's outdated and doesn't seem supported.

I propose to shut down the https://asyncio.readthedocs.io site immediately and, if desired, work on merging any good content/tutorials to docs.python.org.

cc @vstinner @GMLudo

**Comment by vstinner** [comment]
I am fine with that ;-)

**Comment by vstinner** [comment]
But rather than removing it immediately, maybe rewrite the doc to put a single link pointing to http://docs.python.org/dev/library/asyncio.html and wait one month before revoving https://asyncio.readthedocs.io/ ? You can do that immediately, remove content and rewrite index.rst.

**Comment by 1st1** [comment]
Alright, works for me.

**Comment by matrixise** [comment]
@vstinner I have just discovered this issue, now, in 2021, maybe we could shut down the site.

**Comment by vstinner** [comment]
I shut down the project: https://github.com/asyncio-docs/asyncio-doc/issues/33

**Comment by vstinner** [comment]
docs.python.org/dev/library/asyncio.html has been redesigned: it's now way better, it contains nice examples, and it's more up to date than this documentation.

I shut down the project. I removed http://asyncio.readthedocs.io/, I closed all PRs, I closed all issues. I archive the project.
