### ISSUE TITLE
aiohttp examples should use async context manager for session creation

### ISSUE THREAD

**Issue by asvetlov** [asyncio-docs/asyncio-doc#9]
E.g. instead of 

```
with aiohttp.ClientSession() as session:
    ...
```

Use

```
async with aiohttp.ClientSession() as session:
    ...
```

Also please be consistent: either pass loop everywhere (`aiohttp.Timeout(5, loop=loop)`, `asyncio.gather(*tasks, loop=loop)`) or don't pass it at all.

For first case calling `asyncio.set_event_loop(None)` at very begin of the program effectively checks that loop is passed to any call where it's required.

**Comment by vstinner** [comment]
Hi Andrew! Would you mind to send a pull request please?

**Comment by asvetlov** [comment]
Sure, but the question is: do you prefer explicit loop or not?
In all my code I pass loop explicitly because I've found it as best practice for writing safe code and avoiding stupid mistakes.
On other hand it may be too complex for beginners.

**Comment by ludovic-gasc** [comment]
For me, ok for explicit loop, most AsyncIO libraries do that.

**Comment by vstinner** [comment]
I shut down the project: https://github.com/asyncio-docs/asyncio-doc/issues/33
